title: My Engineering Docs
description: Portfolio of [Your Name]
url: "https://popest.github.io" # Replace with your URL

# The critical line to switch themes
remote_theme: just-the-docs/just-the-docs

# Enable the search bar (best feature of this theme!)
search_enabled: true

# Visual settings
color_scheme: nord_theme # uses custom theme
callouts:
  warning:
    title: Note
    color: red
